paths:
  roms: roms
  models: working/models
  recordings: working/recordings
  savestates: working/savestates

training:
  game: Airstriker-Genesis-v0
  savestate: Level1
  total_timesteps: 1000000
  num_envs: 1
  population_size: 128

log_level: INFO

upload:
  url: https://speedlab.datenwissenschaften.com/api
  api_key: null

ui:
  enable: true
  host: 127.0.0.1
  port: 18080
